export const ALLMERCHANTS_REGISTER_REQUEST = "ALLMERCHANTS_REGISTER_REQUEST";
export const ALLMERCHANTS_REGISTER_SUCCESS = "ALLMERCHANTS_REGISTER_SUCCESS";
export const ALLMERCHANTS_REGISTER_FAIL = "ALLMERCHANTS_REGISTER_FAIL";
