export const ADD_TOCART_REQUEST = "ADD_TOCART_REQUEST";
export const ADD_TOCART_SUCCESS = "ADD_TOCART_SUCCESS";
export const REMOVE_FROMCART_SUCCESS = "REMOVE_FROMCART_SUCCESS";
export const CLEAR_ITEMFROMCART_SUCCESS = "CLEAR_ITEMFROMCART_SUCCESS";
export const ADD_TOCART_FAIL = "ADD_TOCART_FAIL";
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS";
