export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";

export const CUSTOMER_SIGNIN_REQUEST = "CUSTOMER_SIGNIN_REQUEST";
export const CUSTOMER_SIGNIN_SUCCESS = "CUSTOMER_SIGNIN_SUCCESS";
export const CUSTOMER_SIGNIN_FAIL = "CUSTOMER_SIGNIN_FAIL";
export const CUSTOMER_SIGNOUT = "CUSTOMER_SIGNOUT";

export const CUSTOMERS_UPDATEPASSWORD_REQUEST =
  "CUSTOMERS_UPDATEPASSWORD_REQUEST";
export const CUSTOMERS_UPDATEPASSWORD_SUCCESS =
  "CUSTOMERS_UPDATEPASSWORD_SUCCESS";
export const CUSTOMERS_UPDATEPASSWORD_FAIL = "CUSTOMERS_UPDATEPASSWORD_FAIL";

export const CUSTOMERS_RESETPASSWORD_REQUEST =
  "CUSTOMERS_RESETPASSWORD_REQUEST";
export const CUSTOMERS_RESETPASSWORD_SUCCESS =
  "CUSTOMERS_RESETPASSWORD_SUCCESS";
export const CUSTOMERS_RESETPASSWORD_FAIL = "CUSTOMERS_RESETPASSWORD_FAIL";

export const CUSTOMERS_UPDATEPROFILE_REQUEST =
  "CUSTOMERS_UPDATEPROFILE_REQUEST";
export const CUSTOMERS_UPDATEPROFILE_SUCCESS =
  "CUSTOMERS_UPDATEPROFILE_SUCCESS";
export const CUSTOMERS_UPDATEPROFILE_FAIL = "CUSTOMERS_UPDATEPROFILE_FAIL";

export const CUSTOMERS_DELETEACCOUNT_REQUEST =
  "CUSTOMERS_DELETEACCOUNT_REQUEST";
export const CUSTOMERS_DELETEACCOUNT_SUCCESS =
  "CUSTOMERS_DELETEACCOUNT_SUCCESS";
export const CUSTOMERS_DELETEACCOUNT_FAIL = "CUSTOMERS_DELETEACCOUNT_FAIL";
