export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

export const SET_ITEMDESCRIPTION = "SET_ITEMDESCRIPTION";

export const GET_PRODUCTDETAIL_REQUEST = "GET_PRODUCTDETAIL_REQUEST";
export const GET_PRODUCTDETAIL_SUCCESS = "GET_PRODUCTDETAIL_SUCCESS";
export const GET_PRODUCTDETAIL_FAIL = "GET_PRODUCTDETAIL_FAIL";

export const GET_INCREASEQUANTITY_REQUEST = "GET_INCREASEQUANTITY_REQUEST";
export const GET_INCREASEQUANTITY_SUCCESS = "GET_INCREASEQUANTITY_SUCCESS";
export const GET_INCREASEQUANTITY_FAIL = "GET_INCREASEQUANTITY_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
