export const STORE_REGISTER_REQUEST = "STORE_REGISTER_REQUEST";
export const STORE_REGISTER_SUCCESS = "STORE_REGISTER_SUCCESS";
export const STORE_REGISTER_FAIL = "STORE_REGISTER_FAIL";

export const STORE_INFORMATION_REQUEST = "STORE_INFORMATION_REQUEST";
export const STORE_INFORMATION_SUCCESS = "STORE_INFORMATION_SUCCESS";
export const STORE_INFORMATION_FAIL = "STORE_INFORMATION_FAIL";

export const GET_MERCHANTSTORES_REQUEST = "GET_MERCHANTSTORES_REQUEST";
export const GET_MERCHANTSTORES_SUCCESS = "GET_MERCHANTSTORES_SUCCESS";
export const GET_MERCHANTSTORES_FAIL = "GET_MERCHANTSTORES_FAIL";

export const SET_CURRENT_STORE = "SET_CURRENT_STORE";
export const SET_CUSTOMERCURRENT_STORE = "SET_CUSTOMERCURRENT_STORE";

export const GET_ALLSTORES_REQUEST = "GET_ALLSTORES_REQUEST";
export const GET_ALLSTORES_SUCCESS = "GET_ALLSTORES_SUCCESS";
export const GET_ALLSTORES_FAIL = "GET_ALLSTORES_FAIL";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";

export const GET_INVENTORY_REQUEST = "GET_INVENTORY_REQUEST";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_FAIL = "GET_INVENTORY_FAIL";

export const GET_MERCHANTCUSTOMERS_REQUEST = "GET_MERCHANTCUSTOMERS_REQUEST";
export const GET_MERCHANTCUSTOMERS_SUCCESS = "GET_MERCHANTCUSTOMERS_SUCCESS";
export const GET_MERCHANTCUSTOMERS_FAIL = "GET_MERCHANTCUSTOMERS_FAIL";
