export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_UPDATEPASSWORD_REQUEST = "USER_UPDATEPASSWORD_REQUEST";
export const USER_UPDATEPASSWORD_SUCCESS = "USER_UPDATEPASSWORD_SUCCESS";
export const USER_UPDATEPASSWORD_FAIL = "USER_UPDATEPASSWORD_FAIL";

export const USER_RESETPASSWORD_REQUEST = "USER_RESETPASSWORD_REQUEST";
export const USER_RESETPASSWORD_SUCCESS = "USER_RESETPASSWORD_SUCCESS";
export const USER_RESETPASSWORD_FAIL = "USER_RESETPASSWORD_FAIL";

export const USER_UPDATEPROFILE_REQUEST = "USER_UPDATEPROFILE_REQUEST";
export const USER_UPDATEPROFILE_SUCCESS = "USER_UPDATEPROFILE_SUCCESS";
export const USER_UPDATEPROFILE_FAIL = "USER_UPDATEPROFILE_FAIL";

export const USER_LOGIN_WITH_GOOGLE_REQUEST = "USER_LOGIN_WITH_GOOGLE_REQUEST";
export const USER_LOGIN_WITH_GOOGLE_SUCCESS = "USER_LOGIN_WITH_GOOGLE_SUCCESS";
export const USER_LOGIN_WITH_GOOGLE_FAIL = "USER_LOGIN_WITH_GOOGLE_FAIL";

export const USER_DELETEACCOUNT_REQUEST = "USER_DELETEACCOUNT_REQUEST";
export const USER_DELETEACCOUNT_SUCCESS = "USER_DELETEACCOUNT_SUCCESS";
export const USER_DELETEACCOUNT_FAIL = "USER_DELETEACCOUNT_FAIL";
